// apps/desktop/src/pages/market/Market.vue
<script setup lang="ts">
// 行情 · 板块视角(全市场快照):全A涨跌广度 + 行业板块卡网格 + 涨跌排行 + 下钻抽屉
// (板块→成分股→个股日K)。数据全来自 api 全市场快照(engine 按 PIT 聚合);缺数据诚实空。
// 注:个股叶子用日K(Candles);北向「主力净流入」需 moneyflow(无),v1 不展示资金流向卡。
import { computed, onMounted, ref } from 'vue';
import { api } from '../../api/client';
import { useAppStore } from '../../stores/app';
import { fmt } from '../../lib/format';
import PageHero from '../../ui/PageHero.vue';
import Sparkline from '../../ui/charts/Sparkline.vue';
import Candles from '../../ui/charts/Candles.vue';
import Icon from '../../shell/Icon.vue';

const app = useAppStore();

interface Sector {
  name: string;
  chg: number;
  count: number;
  up: number;
  down: number;
  lead: string;
  lead_chg: number;
  spark: number[];
}
interface Breadth {
  total: number;
  up: number;
  down: number;
  flat: number;
  avg_chg: number;
}

const loading = ref(false);
const error = ref<string | null>(null);
const asof = ref<string | null>(null);
const breadth = ref<Breadth | null>(null);
const sectors = ref<Sector[]>([]);
const sort = ref<'desc' | 'asc'>('desc'); // 涨幅优先 / 跌幅优先

// 下钻抽屉:板块 → 成分股 → 个股日K
const openSector = ref<Sector | null>(null);
const constituents = ref<any[]>([]);
const loadingCons = ref(false);
const selStock = ref<{ stock_code: string; name?: string | null } | null>(null);
const bars = ref<any[]>([]);
const loadingK = ref(false);

// 板块涨跌家数(从 sectors 派生,纯展示)+ 抽屉成分股上涨/下跌数。
const sectorBreadth = computed(() => ({
  up: sectors.value.filter((s) => s.chg > 0).length,
  down: sectors.value.filter((s) => s.chg < 0).length,
}));
const consBreadth = computed(() => ({
  up: constituents.value.filter((c) => (c.chg ?? 0) > 0).length,
  down: constituents.value.filter((c) => (c.chg ?? 0) < 0).length,
}));

async function loadSnapshot() {
  loading.value = true;
  error.value = null;
  try {
    const r = await api.marketSnapshot();
    asof.value = r?.asof ?? null;
    breadth.value = r?.breadth ?? null;
    sectors.value = r?.sectors ?? [];
  } catch (e) {
    error.value = String(e);
    breadth.value = null;
    sectors.value = [];
  } finally {
    loading.value = false;
  }
}

const sortedSectors = computed(() => {
  const s = [...sectors.value];
  s.sort((a, b) => (sort.value === 'desc' ? b.chg - a.chg : a.chg - b.chg));
  return s;
});
const maxAbsChg = computed(() =>
  sectors.value.reduce((m, s) => Math.max(m, Math.abs(s.chg)), 0.01),
);

function sparkColor(chg: number): string {
  return chg >= 0 ? 'var(--pnl-up)' : 'var(--pnl-down)';
}
function pctTxt(v: number | null | undefined): string {
  return v == null ? '—' : `${v >= 0 ? '+' : ''}${v.toFixed(2)}%`;
}

async function openDrill(sec: Sector) {
  openSector.value = sec;
  selStock.value = null;
  bars.value = [];
  constituents.value = [];
  loadingCons.value = true;
  try {
    const r = await api.marketSector(sec.name);
    constituents.value = r?.constituents ?? [];
  } catch {
    constituents.value = [];
  } finally {
    loadingCons.value = false;
  }
}
function closeDrill() {
  openSector.value = null;
  selStock.value = null;
}
async function pickStock(s: { stock_code: string; name?: string | null }) {
  selStock.value = s;
  loadingK.value = true;
  bars.value = [];
  try {
    const r = await api.prices(s.stock_code, { adjust: 'qfq', limit: 120 });
    bars.value = r?.rows ?? [];
  } catch {
    bars.value = [];
  } finally {
    loadingK.value = false;
  }
}
const candleData = computed(() =>
  bars.value.map((b) => ({ o: b.open, h: b.high, l: b.low, c: b.close, v: b.volume ?? 0 })),
);

onMounted(() => {
  if (app.onboardingDone) loadSnapshot();
});
</script>

<template>
  <PageHero title="行情" sub="沪深A股 · 行业板块视角 · 收盘后全市场快照">
    <template #right>
      <span v-if="asof" class="mono src-tag">{{ asof }} 收盘</span>
      <button class="btn btn-secondary btn-sm" :disabled="loading" @click="loadSnapshot">
        <Icon name="refresh" :size="13" /> {{ loading ? '刷新中…' : '刷新' }}
      </button>
    </template>
  </PageHero>

  <div class="page-body">
    <p v-if="error" class="banner banner-err">{{ error }}</p>

    <!-- 全 A 涨跌广度(替代大盘指数条;真实) -->
    <div v-if="breadth" class="breadth card">
      <div class="bd-cell">
        <div class="bd-k">全 A 平均涨跌</div>
        <div class="bd-v mono" :class="app.pnlClass(breadth.avg_chg)">
          {{ pctTxt(breadth.avg_chg) }}
        </div>
      </div>
      <div class="bd-cell">
        <div class="bd-k">上涨</div>
        <div class="bd-v mono" :class="app.pnlClass(1)">{{ breadth.up }}</div>
      </div>
      <div class="bd-cell">
        <div class="bd-k">下跌</div>
        <div class="bd-v mono" :class="app.pnlClass(-1)">{{ breadth.down }}</div>
      </div>
      <div class="bd-cell">
        <div class="bd-k">平盘</div>
        <div class="bd-v mono">{{ breadth.flat }}</div>
      </div>
      <div class="bd-bar">
        <div class="bd-up" :style="{ width: (breadth.up / breadth.total) * 100 + '%' }" />
        <div class="bd-flat" :style="{ width: (breadth.flat / breadth.total) * 100 + '%' }" />
        <div class="bd-down" :style="{ width: (breadth.down / breadth.total) * 100 + '%' }" />
      </div>
      <span class="bd-total mono">{{ breadth.total }} 只</span>
    </div>

    <div v-if="sectors.length" class="cols">
      <!-- 左:板块卡网格 -->
      <div class="sectors-col">
        <div class="sectors-head">
          <div class="sec-label-row">
            <div class="sec-label">行业板块</div>
            <span class="sec-breadth mono">
              <span :class="app.pnlClass(1)">{{ sectorBreadth.up }} 涨</span>
              <span :class="app.pnlClass(-1)">{{ sectorBreadth.down }} 跌</span>
            </span>
          </div>
          <div class="segmented">
            <button :class="{ on: sort === 'desc' }" @click="sort = 'desc'">涨幅</button>
            <button :class="{ on: sort === 'asc' }" @click="sort = 'asc'">跌幅</button>
          </div>
        </div>
        <div class="sector-grid">
          <button
            v-for="s in sortedSectors"
            :key="s.name"
            class="card sector-card"
            @click="openDrill(s)"
          >
            <div class="sc-top">
              <div class="sc-name-wrap">
                <div class="sc-name">{{ s.name }}</div>
                <div class="sc-lead">领涨 {{ s.lead }}</div>
              </div>
              <div class="sc-chg mono" :class="app.pnlClass(s.chg)">{{ pctTxt(s.chg) }}</div>
            </div>
            <Sparkline
              v-if="s.spark.length >= 2"
              :values="s.spark"
              :width="206"
              :height="28"
              :color="sparkColor(s.chg)"
            />
            <div v-else class="sc-nospark" />
            <div class="sc-foot">
              <span class="sc-cap">涨 / 跌 家数</span>
              <span class="sc-ud mono">
                <span :class="app.pnlClass(1)">{{ s.up }}</span>
                <span class="sc-sep">/</span>
                <span :class="app.pnlClass(-1)">{{ s.down }}</span>
              </span>
            </div>
          </button>
        </div>
      </div>

      <!-- 右:板块涨跌排行 -->
      <div class="card rank-card">
        <div class="card-head">
          <div>
            <h3 class="card-title">板块涨跌排行</h3>
            <span class="card-sub">今日 · 行业等权</span>
          </div>
          <span class="ch-tag"><i style="background: var(--pnl-up)" />PnL</span>
        </div>
        <div class="rank-list">
          <button
            v-for="(s, i) in [...sectors].sort((a, b) => b.chg - a.chg)"
            :key="s.name"
            class="rank-row"
            @click="openDrill(s)"
          >
            <span class="rank-n mono" :class="{ top: i < 3 }">{{ i + 1 }}</span>
            <div class="rank-main">
              <div class="rank-r1">
                <span class="rank-name">{{ s.name }}</span>
                <span class="rank-chg mono" :class="app.pnlClass(s.chg)">{{ pctTxt(s.chg) }}</span>
              </div>
              <div class="rank-bar">
                <div
                  class="rank-fill"
                  :style="{
                    width: Math.min(100, (Math.abs(s.chg) / maxAbsChg) * 100) + '%',
                    background: sparkColor(s.chg),
                  }"
                />
              </div>
            </div>
          </button>
        </div>
        <p class="rank-note cap">资金流向待北向数据接入(主力净流入需 moneyflow,本数据源未授权)。</p>
      </div>
    </div>

    <!-- 诚实空 -->
    <div v-else-if="!loading" class="card">
      <div class="empty">
        <div class="empty-icon"><Icon name="market" :size="20" /></div>
        <div class="empty-title">暂无全市场快照</div>
        <div class="empty-desc">
          需先到「设置 → 数据源」建立本地缓存(含日线 + 行业);建好后这里按行业聚合展示板块视角。
        </div>
      </div>
    </div>

    <p class="disclaimer">
      板块视角按本地缓存的日线 + 个股行业聚合(收盘价口径);仅供研究,非投资建议。个股行业取自数据源
      基础分类,申万一级与北向资金流向为后续增强。
    </p>

    <!-- 下钻抽屉:板块 → 成分股 → 个股日K -->
    <template v-if="openSector">
      <div class="drawer-scrim" @click="closeDrill" />
      <aside class="drawer card">
        <div class="drawer-head">
          <button v-if="selStock" class="dh-back" title="返回成分股" @click="selStock = null">
            <Icon name="chevR" :size="16" style="transform: rotate(180deg)" />
          </button>
          <div class="dh-title">
            <template v-if="selStock">
              <span class="dh-name">{{ selStock.name || selStock.stock_code }}</span>
              <span class="dh-code mono">{{ selStock.stock_code }}</span>
            </template>
            <template v-else>
              <span class="dh-name">{{ openSector.name }}</span>
              <span class="dh-code mono" :class="app.pnlClass(openSector.chg)">{{
                pctTxt(openSector.chg)
              }}</span>
              <span class="dh-sub">{{ constituents.length || openSector.count }} 只成分股</span>
            </template>
          </div>
          <button class="dh-close" title="关闭" @click="closeDrill">
            <Icon name="alert" :size="14" style="display: none" />✕
          </button>
        </div>

        <div class="drawer-body">
          <!-- 个股日K -->
          <template v-if="selStock">
            <div v-if="loadingK" class="empty"><div class="empty-title">加载 K 线…</div></div>
            <Candles v-else-if="bars.length" :data="candleData" :height="320" :ma="[5, 10, 20]" />
            <div v-else class="empty">
              <div class="empty-icon"><Icon name="db" :size="20" /></div>
              <div class="empty-title">本地无该股日线缓存</div>
              <div class="empty-desc">到「设置 → 数据源」建立缓存后查看日K。</div>
            </div>
          </template>
          <!-- 成分股列表 -->
          <template v-else>
            <div v-if="loadingCons" class="empty"><div class="empty-title">加载成分股…</div></div>
            <template v-else-if="constituents.length">
              <div class="cons-stats">
                <div class="cs">
                  <span class="cs-k cap">上涨</span>
                  <span class="cs-v mono" :class="app.pnlClass(1)">{{ consBreadth.up }}</span>
                </div>
                <div class="cs">
                  <span class="cs-k cap">下跌</span>
                  <span class="cs-v mono" :class="app.pnlClass(-1)">{{ consBreadth.down }}</span>
                </div>
                <div class="cs">
                  <span class="cs-k cap">成分股</span>
                  <span class="cs-v mono">{{ constituents.length }}</span>
                </div>
              </div>
              <table class="dt dt-compact">
                <thead>
                  <tr>
                    <th>名称 / 代码</th>
                    <th class="num">现价</th>
                    <th class="num">涨跌幅</th>
                    <th class="num">换手</th>
                    <th style="width: 28px" />
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="c in constituents" :key="c.stock_code" @click="pickStock(c)">
                    <td>
                      <div class="cons-name">
                        <span class="nm">{{ c.name || c.stock_code }}</span>
                        <span class="cd mono">{{ c.stock_code }}</span>
                      </div>
                    </td>
                    <td class="num">{{ c.price == null ? '—' : fmt(c.price) }}</td>
                    <td class="num" :class="app.pnlClass(c.chg)">{{ pctTxt(c.chg) }}</td>
                    <td class="num c2">{{ c.turnover == null ? '—' : c.turnover + '%' }}</td>
                    <td class="c-chev">›</td>
                  </tr>
                </tbody>
              </table>
            </template>
            <div v-else class="empty">
              <div class="empty-title">该板块暂无成分股数据</div>
            </div>
            <p class="drawer-hint cap">点击任意成分股查看日K走势</p>
          </template>
        </div>
      </aside>
    </template>
  </div>
</template>

<style scoped>
.page-body {
  padding: 28px;
  display: flex;
  flex-direction: column;
  gap: 20px;
  position: relative;
}
.src-tag {
  font-size: var(--fs-sub);
  color: var(--text-3);
}
.banner {
  margin: 0;
  padding: 9px 14px;
  border-radius: var(--r-md);
  font-size: var(--fs-sub);
}
.banner-err {
  color: var(--status-err);
  background: var(--status-err-bg);
  border: 0.5px solid var(--status-err);
}

/* 全A广度条 */
.breadth {
  display: flex;
  align-items: center;
  gap: 24px;
  padding: 14px 20px;
}
.bd-cell {
  flex: none;
}
.bd-k {
  font-size: var(--fs-cap);
  color: var(--text-3);
  margin-bottom: 3px;
}
.bd-v {
  font-size: 16px;
  font-weight: 600;
  color: var(--text-1);
}
.bd-bar {
  flex: 1;
  height: 8px;
  border-radius: 4px;
  overflow: hidden;
  display: flex;
  background: var(--bg-input);
}
.bd-up {
  background: var(--pnl-up);
}
.bd-flat {
  background: var(--text-3);
  opacity: 0.4;
}
.bd-down {
  background: var(--pnl-down);
}
.bd-total {
  flex: none;
  font-size: var(--fs-cap);
  color: var(--text-3);
}

/* 两栏:板块网格 + 排行 */
.cols {
  display: grid;
  grid-template-columns: minmax(0, 1fr) 360px;
  gap: 20px;
  align-items: start;
}
.sectors-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 14px;
}
.sector-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(238px, 1fr));
  gap: 14px;
}
.sector-card {
  text-align: left;
  cursor: pointer;
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.sector-card:hover {
  border-color: var(--border-strong);
}
.sc-top {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 8px;
}
.sc-name {
  font-size: 14px;
  font-weight: 600;
  color: var(--text-1);
}
.sc-chg {
  font-size: 18px;
  font-weight: 700;
  letter-spacing: -0.01em;
}
.sc-nospark {
  height: 28px;
}
.sc-foot {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding-top: 11px;
  border-top: 0.5px solid var(--border-faint);
}
.sc-lead {
  font-size: 10.5px;
  color: var(--text-3);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.sc-ud {
  font-size: 12px;
  flex: none;
}
.sec-label-row {
  display: flex;
  align-items: center;
  gap: 10px;
}
.sec-breadth {
  display: inline-flex;
  gap: 8px;
  font-size: 11px;
}
.sc-name-wrap {
  display: flex;
  flex-direction: column;
  gap: 2px;
  min-width: 0;
  flex: 1;
}
.sc-cap {
  font-size: 10px;
  color: var(--text-3);
}
.cons-stats {
  display: flex;
  gap: 28px;
  padding: 10px 14px;
  border-bottom: 0.5px solid var(--border-faint);
}
.cons-stats .cs {
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.cons-stats .cs-v {
  font-size: 14px;
  font-weight: 600;
}
.c-chev {
  color: var(--text-3);
  text-align: center;
  width: 28px;
}
.sc-sep {
  color: var(--text-3);
  margin: 0 3px;
}

/* 排行 */
.rank-list {
  padding: 6px 8px 0;
}
.rank-row {
  display: flex;
  align-items: center;
  gap: 11px;
  width: 100%;
  padding: 8px 10px;
  border-radius: var(--r-sm);
  cursor: pointer;
  text-align: left;
}
.rank-row:hover {
  background: var(--bg-elevated);
}
.rank-n {
  width: 18px;
  text-align: center;
  font-size: 12px;
  font-weight: 700;
  color: var(--text-3);
  flex: none;
}
.rank-n.top {
  color: var(--accent);
}
.rank-main {
  flex: 1;
  min-width: 0;
}
.rank-r1 {
  display: flex;
  justify-content: space-between;
  margin-bottom: 5px;
}
.rank-name {
  font-size: 12.5px;
  color: var(--text-1);
  font-weight: 500;
}
.rank-chg {
  font-size: 12.5px;
  font-weight: 600;
}
.rank-bar {
  height: 4px;
  border-radius: 2px;
  background: var(--bg-input);
  overflow: hidden;
}
.rank-fill {
  height: 100%;
  border-radius: 2px;
  opacity: 0.85;
}
.rank-note {
  padding: 12px 16px;
  color: var(--text-3);
}

/* 下钻抽屉 */
.drawer-scrim {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.4);
  z-index: 60;
}
.drawer {
  position: fixed;
  top: var(--titlebar-h);
  right: 0;
  bottom: var(--statusbar-h);
  width: 560px;
  max-width: 90vw;
  z-index: 61;
  display: flex;
  flex-direction: column;
  border-radius: 0;
  animation: drawer-in 160ms var(--ease-out);
}
@keyframes drawer-in {
  from {
    transform: translateX(20px);
    opacity: 0.6;
  }
  to {
    transform: translateX(0);
    opacity: 1;
  }
}
.drawer-head {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 14px 18px;
  border-bottom: 0.5px solid var(--border);
}
.dh-back,
.dh-close {
  width: 30px;
  height: 30px;
  border-radius: var(--r-sm);
  border: none;
  background: transparent;
  color: var(--text-2);
  cursor: pointer;
  display: grid;
  place-items: center;
  flex: none;
}
.dh-back:hover,
.dh-close:hover {
  background: var(--bg-elevated);
  color: var(--text-1);
}
.dh-title {
  flex: 1;
  display: flex;
  align-items: baseline;
  gap: 10px;
  min-width: 0;
}
.dh-name {
  font-size: 15px;
  font-weight: 600;
  color: var(--text-1);
}
.dh-code {
  font-size: 12px;
  color: var(--text-3);
}
.dh-sub {
  font-size: 11.5px;
  color: var(--text-3);
}
.drawer-body {
  flex: 1;
  overflow: auto;
  padding: 12px 0;
}
.cons-name {
  display: flex;
  flex-direction: column;
  gap: 1px;
}
.cons-name .nm {
  font-weight: 500;
  color: var(--text-1);
  font-size: 12.5px;
}
.cons-name .cd {
  font-size: 10.5px;
  color: var(--text-3);
}
.c2 {
  color: var(--text-2);
}
.drawer-hint {
  padding: 12px 16px;
  color: var(--text-3);
}
.disclaimer {
  margin: 4px 0 0;
  color: var(--text-3);
  font-size: var(--fs-cap);
}
@media (max-width: 1080px) {
  .cols {
    grid-template-columns: 1fr;
  }
}
</style>

// docs/design_handoff_sinan/design_source/src/pages/market.jsx
/* ============================================================
   司南 Sinan — 行情 Market (板块视角)
   左: 行业板块卡片网格(涨跌幅 + 主力资金净流入/流出)
   右: 今日行业板块涨跌幅排行榜
   ============================================================ */
function Market() {
  const { inv } = React.useContext(AppCtx);
  const [sort, setSort] = React.useState("涨跌幅");
  const [openSector, setOpenSector] = React.useState(null);
  const [selStock, setSelStock] = React.useState(null);

  const openDrill = (s) => { setSelStock(null); setOpenSector(s); };
  const closeDrill = () => { setOpenSector(null); setSelStock(null); };

  // 排序后的板块(卡片网格随之联动)
  const sorted = React.useMemo(() => {
    const arr = [...SECTORS];
    if (sort === "涨跌幅") arr.sort((a, b) => b.chg - a.chg);
    else if (sort === "资金流入") arr.sort((a, b) => b.flow - a.flow);
    else arr.sort((a, b) => b.turnover - a.turnover);
    return arr;
  }, [sort]);

  const upN = SECTORS.filter((s) => s.chg > 0).length;
  const downN = SECTORS.filter((s) => s.chg < 0).length;
  const netFlow = SECTORS.reduce((a, b) => a + b.flow, 0);

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%", position: "relative" }}>
      <PageHero title="行情" sub="沪深A股 · 行业板块概览 · 收盘后数据"
        right={<>
          <span className="mono" style={{ fontSize: 12, color: "var(--text-3)" }}>15:08 收盘</span>
          <Button sm icon={I.refresh}>刷新</Button>
        </>} />

      {/* 大盘指数条 */}
      <div style={{ display: "flex", gap: 0, margin: "18px 28px 0", borderRadius: "var(--r-lg)",
        overflow: "hidden", border: "0.5px solid var(--border)", background: "var(--glass-card)",
        WebkitBackdropFilter: "var(--glass-blur)", backdropFilter: "var(--glass-blur)", boxShadow: "var(--hi-edge), var(--shadow-card)" }}>
        {INDICES.map((ix, i) => (
          <div key={ix.code} style={{ flex: 1, padding: "13px 18px", borderRight: i < INDICES.length - 1 ? "0.5px solid var(--border-faint)" : "none",
            display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12 }}>
            <div>
              <div style={{ fontSize: 12.5, fontWeight: 600, color: "var(--text-1)" }}>{ix.name}</div>
              <div className="mono" style={{ fontSize: 10.5, color: "var(--text-3)", marginTop: 2 }}>{ix.code}</div>
            </div>
            <div style={{ textAlign: "right" }}>
              <div className={"mono " + pnlClass(ix.chg, inv)} style={{ fontSize: 16, fontWeight: 600 }}>{fmt(ix.price)}</div>
              <div className={"mono " + pnlClass(ix.chg, inv)} style={{ fontSize: 11.5, marginTop: 2 }}>{fmtPct(ix.chg)}</div>
            </div>
          </div>
        ))}
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) 388px", gap: 20, padding: 28, flex: 1, minHeight: 0, overflow: "auto" }}>
        {/* 左: 板块卡片网格 */}
        <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
              <span className="sec-label" style={{ padding: 0, whiteSpace: "nowrap" }}>行业板块</span>
              <span style={{ display: "inline-flex", gap: 10, fontSize: 11.5, whiteSpace: "nowrap" }}>
                <span className={pnlClass(1, inv)}>{upN} 涨</span>
                <span className={pnlClass(-1, inv)}>{downN} 跌</span>
              </span>
            </div>
            <Segmented options={["涨跌幅", "资金流入", "成交额"]} value={sort} onChange={setSort} />
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(238px, 1fr))", gap: 14 }}>
            {sorted.map((s) => <SectorCard key={s.name} s={s} inv={inv} onClick={() => openDrill(s)} />)}
          </div>
        </div>

        {/* 右: 涨跌幅排行榜 */}
        <div style={{ display: "flex", flexDirection: "column", gap: 16, minWidth: 0 }}>
          <Card title="板块涨跌幅排行" sub="今日 · 申万一级行业"
            right={<span className="ch-tag"><i style={{ background: "var(--pnl-up)" }} />PnL</span>} pad={false}>
            <div style={{ padding: "6px 8px" }}>
              {[...SECTORS].sort((a, b) => b.chg - a.chg).map((s, i) => <RankRow key={s.name} s={s} rank={i + 1} inv={inv} onClick={() => openDrill(s)} />)}
            </div>
          </Card>

          <Card title="主力资金净流向" sub="单位 亿元 · 正流入 / 负流出">
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {[...SECTORS].sort((a, b) => b.flow - a.flow).slice(0, 6).map((s) => <FlowRow key={s.name} s={s} inv={inv} />)}
              <div className="hairline" style={{ margin: "2px 0" }} />
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <span style={{ fontSize: 12, color: "var(--text-2)" }}>板块合计净流入</span>
                <span className={"mono " + pnlClass(netFlow, inv)} style={{ fontSize: 14, fontWeight: 600 }}>{fmtSigned(netFlow, 1)} 亿</span>
              </div>
            </div>
          </Card>
        </div>
      </div>

      {openSector && (
        <SectorDrawer sector={openSector} selStock={selStock} setSelStock={setSelStock} onClose={closeDrill} inv={inv} />
      )}
    </div>
  );
}

// ---- 板块卡片 ----
function SectorCard({ s, inv, onClick }) {
  const cls = pnlClass(s.chg, inv);
  const flowCls = pnlClass(s.flow, inv);
  const lineColor = s.chg >= 0
    ? (inv ? "var(--pnl-down)" : "var(--pnl-up)")
    : (inv ? "var(--pnl-up)" : "var(--pnl-down)");
  return (
    <div className="card" onClick={onClick} style={{ padding: 16, display: "flex", flexDirection: "column", gap: 13, cursor: "pointer", transition: "border-color var(--t-fast)" }}
      onMouseEnter={(e) => { e.currentTarget.style.borderColor = "var(--border-strong)"; }}
      onMouseLeave={(e) => { e.currentTarget.style.borderColor = ""; }}>
      <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 8 }}>
        <div style={{ minWidth: 0 }}>
          <div style={{ fontSize: 14, fontWeight: 600, color: "var(--text-1)" }}>{s.name}</div>
          <div style={{ fontSize: 10.5, color: "var(--text-3)", marginTop: 3 }}>领涨 {s.lead}</div>
        </div>
        <div className={"mono " + cls} style={{ fontSize: 19, fontWeight: 700, letterSpacing: "-0.01em", flex: "none" }}>{fmtPct(s.chg)}</div>
      </div>

      <Sparkline values={s.spark} width={206} height={30} color={lineColor} />

      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", paddingTop: 11, borderTop: "0.5px solid var(--border-faint)" }}>
        <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
          <span style={{ fontSize: 10, color: "var(--text-3)" }}>主力净{s.flow >= 0 ? "流入" : "流出"}</span>
          <span className={"mono " + flowCls} style={{ fontSize: 13, fontWeight: 600 }}>{fmtSigned(s.flow, 1)} 亿</span>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 2, alignItems: "flex-end" }}>
          <span style={{ fontSize: 10, color: "var(--text-3)" }}>涨 / 跌 家数</span>
          <span className="mono" style={{ fontSize: 12 }}>
            <span className={pnlClass(1, inv)}>{s.up}</span>
            <span style={{ color: "var(--text-3)" }}> / </span>
            <span className={pnlClass(-1, inv)}>{s.down}</span>
          </span>
        </div>
      </div>
    </div>
  );
}

// ---- 排行榜行 ----
function RankRow({ s, rank, inv, onClick }) {
  const cls = pnlClass(s.chg, inv);
  const top3 = rank <= 3;
  const barColor = s.chg >= 0
    ? (inv ? "var(--pnl-down)" : "var(--pnl-up)")
    : (inv ? "var(--pnl-up)" : "var(--pnl-down)");
  const maxAbs = 4.2;
  const w = Math.min(100, Math.abs(s.chg) / maxAbs * 100);
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 11, padding: "8px 10px", borderRadius: "var(--r-sm)", cursor: "pointer" }}
      onClick={onClick}
      onMouseEnter={(e) => e.currentTarget.style.background = "var(--bg-elevated)"}
      onMouseLeave={(e) => e.currentTarget.style.background = "transparent"}>
      <span className="mono" style={{ width: 18, textAlign: "center", fontSize: 12, fontWeight: 700,
        color: top3 ? "var(--accent)" : "var(--text-3)" }}>{rank}</span>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 5 }}>
          <span style={{ fontSize: 12.5, color: "var(--text-1)", fontWeight: 500 }}>{s.name}</span>
          <span className={"mono " + cls} style={{ fontSize: 12.5, fontWeight: 600 }}>{fmtPct(s.chg)}</span>
        </div>
        <div style={{ height: 4, borderRadius: 2, background: "var(--bg-input)", overflow: "hidden" }}>
          <div style={{ width: w + "%", height: "100%", background: barColor, borderRadius: 2, opacity: 0.85 }} />
        </div>
      </div>
    </div>
  );
}

// ---- 资金流向行 ----
function FlowRow({ s, inv }) {
  const cls = pnlClass(s.flow, inv);
  const maxAbs = 38.6;
  const w = Math.min(100, Math.abs(s.flow) / maxAbs * 100);
  const barColor = s.flow >= 0
    ? (inv ? "var(--pnl-down)" : "var(--pnl-up)")
    : (inv ? "var(--pnl-up)" : "var(--pnl-down)");
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 11 }}>
      <span style={{ width: 60, fontSize: 12, color: "var(--text-2)", flex: "none", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{s.name}</span>
      <div style={{ flex: 1, height: 6, borderRadius: 3, background: "var(--bg-input)", overflow: "hidden" }}>
        <div style={{ width: w + "%", height: "100%", background: barColor, borderRadius: 3, opacity: 0.85 }} />
      </div>
      <span className={"mono " + cls} style={{ width: 58, textAlign: "right", fontSize: 12, fontWeight: 500, flex: "none" }}>{fmtSigned(s.flow, 1)}</span>
    </div>
  );
}

window.Market = Market;

// ============================================================
// 下钻抽屉: 板块 → 成分股列表 → 个股当日分时
// ============================================================
function SectorDrawer({ sector, selStock, setSelStock, onClose, inv }) {
  const stocks = React.useMemo(() => enrichStocks(sector.name, sector.chg), [sector.name]);

  // Esc 关闭
  React.useEffect(() => {
    const h = (e) => { if (e.key === "Escape") { selStock ? setSelStock(null) : onClose(); } };
    window.addEventListener("keydown", h);
    return () => window.removeEventListener("keydown", h);
  }, [selStock]);

  return (
    <>
      <div className="drawer-scrim" onClick={onClose} />
      <div className="drawer">
        {/* 头部 */}
        <div className="drawer-head">
          {selStock ? (
            <button className="drawer-iconbtn" onClick={() => setSelStock(null)} title="返回成分股">{I.back}</button>
          ) : (
            <span style={{ width: 30, height: 30, borderRadius: "var(--r-sm)", display: "grid", placeItems: "center",
              background: "var(--accent-bg)", color: "var(--accent)", flex: "none" }}>{I.market}</span>
          )}
          <div style={{ flex: 1, minWidth: 0 }}>
            {selStock ? (
              <div style={{ display: "flex", alignItems: "baseline", gap: 8 }}>
                <span style={{ fontSize: 15, fontWeight: 600, color: "var(--text-1)" }}>{selStock.name}</span>
                <span className="mono" style={{ fontSize: 11, color: "var(--text-3)" }}>{selStock.code}</span>
              </div>
            ) : (
              <div style={{ display: "flex", alignItems: "baseline", gap: 10 }}>
                <span style={{ fontSize: 15, fontWeight: 600, color: "var(--text-1)" }}>{sector.name}</span>
                <span className={"mono " + pnlClass(sector.chg, inv)} style={{ fontSize: 13, fontWeight: 600 }}>{fmtPct(sector.chg)}</span>
                <span style={{ fontSize: 11.5, color: "var(--text-3)" }}>{stocks.length} 只成分股</span>
              </div>
            )}
          </div>
          <button className="drawer-iconbtn" onClick={onClose} title="关闭">{I.close}</button>
        </div>

        {/* 内容 */}
        <div className="drawer-body">
          {selStock ? <StockDetail stock={selStock} inv={inv} /> : <Constituents stocks={stocks} inv={inv} onPick={setSelStock} />}
        </div>
      </div>
    </>
  );
}

// ---- 成分股列表 ----
function Constituents({ stocks, inv, onPick }) {
  const totalFlow = stocks.reduce((a, b) => a + b.flow, 0);
  return (
    <div>
      <div style={{ padding: "12px 16px", borderBottom: "0.5px solid var(--border)", display: "flex", gap: 22 }}>
        <MiniStat k="主力净流入" v={fmtSigned(totalFlow, 1) + " 亿"} cls={pnlClass(totalFlow, inv)} />
        <MiniStat k="上涨" v={stocks.filter((s) => s.chg > 0).length + " 只"} cls={pnlClass(1, inv)} />
        <MiniStat k="下跌" v={stocks.filter((s) => s.chg < 0).length + " 只"} cls={pnlClass(-1, inv)} />
      </div>
      <table className="dt dt-compact">
        <thead>
          <tr>
            <th>名称 / 代码</th>
            <th className="num">现价</th>
            <th className="num">涨跌幅</th>
            <th className="num">主力净流入</th>
            <th className="num">换手</th>
            <th style={{ width: 30 }}></th>
          </tr>
        </thead>
        <tbody>
          {stocks.map((s) => (
            <tr key={s.code} onClick={() => onPick(s)} style={{ cursor: "pointer" }}>
              <td>
                <div style={{ display: "flex", flexDirection: "column", gap: 1 }}>
                  <span style={{ color: "var(--text-1)", fontWeight: 500, fontSize: 12.5 }}>{s.name}</span>
                  <span className="mono" style={{ fontSize: 10, color: "var(--text-3)" }}>{s.code}</span>
                </div>
              </td>
              <td className="num" style={{ color: "var(--text-1)" }}>{fmt(s.price)}</td>
              <td className="num"><span className={pnlClass(s.chg, inv)}>{fmtPct(s.chg)}</span></td>
              <td className="num"><span className={pnlClass(s.flow, inv)}>{fmtSigned(s.flow, 1)}</span></td>
              <td className="num" style={{ color: "var(--text-2)" }}>{s.turn}%</td>
              <td style={{ color: "var(--text-3)", textAlign: "center" }}>{I.chevR}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <div style={{ padding: "12px 16px", fontSize: 11, color: "var(--text-3)" }}>点击任意成分股查看当日分时走势</div>
    </div>
  );
}

// ---- 个股当日分时 ----
function StockDetail({ stock, inv }) {
  const data = React.useMemo(() => genIntraday(stock.code, stock.prevClose, stock.chg), [stock.code]);
  const chgAmt = stock.price - stock.prevClose;
  const cls = pnlClass(stock.chg, inv);
  const hi = Math.max(...data.price), lo = Math.min(...data.price);
  return (
    <div style={{ padding: "18px 18px 24px" }}>
      {/* 价格头 */}
      <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", marginBottom: 18 }}>
        <div>
          <div className={"mono " + cls} style={{ fontSize: 30, fontWeight: 700, letterSpacing: "-0.01em", lineHeight: 1 }}>{fmt(stock.price)}</div>
          <div className={"mono " + cls} style={{ fontSize: 13, fontWeight: 500, marginTop: 7 }}>
            {chgAmt > 0 ? "+" : ""}{fmt(chgAmt)}　{fmtPct(stock.chg)}
          </div>
        </div>
        <div style={{ display: "flex", gap: 16, alignItems: "center" }}>
          <span style={{ display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11, color: "var(--text-3)" }}>
            <span style={{ width: 12, height: 2, background: stock.chg >= 0 ? (inv ? "var(--pnl-down)" : "var(--pnl-up)") : (inv ? "var(--pnl-up)" : "var(--pnl-down)") }} />价格
          </span>
          <span style={{ display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11, color: "var(--text-3)" }}>
            <span style={{ width: 12, height: 2, background: "#e0b34a" }} />均价
          </span>
        </div>
      </div>

      {/* 分时图 */}
      <Intraday data={data} chg={stock.chg} inv={inv} height={300} />

      {/* 关键指标 */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 10, marginTop: 20 }}>
        {[["昨收", fmt(stock.prevClose)], ["最高", fmt(hi), inv ? "pnl-down" : "pnl-up"], ["最低", fmt(lo), inv ? "pnl-up" : "pnl-down"], ["换手率", stock.turn + "%"],
          ["成交额", stock.amt + "亿"], ["主力净流入", fmtSigned(stock.flow, 1) + "亿", pnlClass(stock.flow, inv)], ["市盈率", stock.pe], ["振幅", ((hi - lo) / stock.prevClose * 100).toFixed(2) + "%"]].map((m, i) => (
          <div key={i} style={{ background: "var(--bg-panel-2)", borderRadius: "var(--r-sm)", padding: "10px 12px" }}>
            <div style={{ fontSize: 10.5, color: "var(--text-3)", marginBottom: 4 }}>{m[0]}</div>
            <div className={"mono " + (m[2] || "")} style={{ fontSize: 13, fontWeight: 600, color: m[2] ? undefined : "var(--text-1)" }}>{m[1]}</div>
          </div>
        ))}
      </div>

      <div style={{ marginTop: 18, display: "flex", gap: 8 }}>
        <Button variant="primary" sm style={{ flex: 1 }}>加入自选</Button>
        <Button sm style={{ flex: 1 }}>查看日K线</Button>
      </div>
    </div>
  );
}

function MiniStat({ k, v, cls }) {
  return (
    <div>
      <div style={{ fontSize: 10.5, color: "var(--text-3)", marginBottom: 3 }}>{k}</div>
      <div className={"mono " + (cls || "")} style={{ fontSize: 13, fontWeight: 600, color: cls ? undefined : "var(--text-1)" }}>{v}</div>
    </div>
  );
}
