// docs/design_handoff_sinan/design_source/src/pages/signals.jsx
/* ============================================================
   司南 Sinan — 信号 Signals
   方向 = Status 通道(买=蓝 卖=橙 持有=灰),综合分 = 中性
   ============================================================ */
function DirTag({ dir }) {
  const map = {
    buy:  { k: "ok",   t: "买入", icon: "▲" },
    sell: { k: "warn", t: "卖出", icon: "▼" },
    hold: { k: "idle", t: "持有", icon: "—" },
  };
  const m = map[dir];
  return (
    <span className={`badge badge-${m.k}`} style={{ height: 20, fontSize: 11.5, paddingInline: 8 }}>
      <span style={{ fontSize: 9 }}>{m.icon}</span>{m.t}
    </span>
  );
}

function ScoreBar({ score }) {
  // 综合分用中性灰阶,不占用任何颜色通道
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 9 }}>
      <span className="mono" style={{ fontSize: 13, fontWeight: 600, color: "var(--text-1)", width: 22 }}>{score}</span>
      <div style={{ width: 56, height: 5, borderRadius: 3, background: "var(--bg-input)", overflow: "hidden" }}>
        <div style={{ width: score + "%", height: "100%", background: score >= 70 ? "var(--text-1)" : "var(--text-3)", borderRadius: 3 }} />
      </div>
    </div>
  );
}

function Signals() {
  const [tab, setTab] = React.useState("通过");
  return (
    <>
      <PageHero title="信号" sub="基于多因子模型 · 2026-06-09 收盘后生成 · 全市场 4,832 只股票"
        right={<Button sm variant="primary" icon={I.refresh}>重新运行</Button>} />
      <div style={{ padding: 28, display: "flex", flexDirection: "column", gap: 20 }}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <Segmented options={[{ value: "通过", label: "入选信号 · 7" }, { value: "拦截", label: "被风控拦截 · 3" }]} value={tab} onChange={setTab} />
          <div style={{ display: "flex", gap: 14, fontSize: 11, color: "var(--text-3)" }}>
            <span className="ch-tag"><i style={{ background: "var(--status-ok)" }} />方向=Status</span>
            <span className="ch-tag"><i style={{ background: "var(--text-2)" }} />综合分=中性</span>
            <span className="ch-tag"><i style={{ background: "var(--pnl-up)" }} />因子贡献=PnL</span>
          </div>
        </div>

        {tab === "通过" ? (
          <Card pad={false}>
            <table className="dt">
              <thead>
                <tr>
                  <th style={{ width: 150 }}>标的</th>
                  <th style={{ width: 78 }}>方向</th>
                  <th style={{ width: 120 }}>综合分</th>
                  <th>因子贡献</th>
                  <th>入选原因</th>
                </tr>
              </thead>
              <tbody>
                {SIGNALS.map((s) => (
                  <SignalRow key={s.code} s={s} />
                ))}
              </tbody>
            </table>
          </Card>
        ) : (
          <Card pad={false}>
            <div style={{ padding: "12px 16px", borderBottom: "0.5px solid var(--border)", display: "flex", alignItems: "center", gap: 8 }}>
              <span style={{ color: "var(--status-warn)", display: "inline-flex" }}>{I.shield}</span>
              <span style={{ fontSize: 12.5, color: "var(--text-2)" }}>以下标的初选入围,但被风控闸拦截,不进入交易候选。风控规则可在<b style={{ color: "var(--text-1)", fontWeight: 500 }}>设置 · 风控</b>中调整。</span>
            </div>
            <table className="dt">
              <thead>
                <tr>
                  <th style={{ width: 150 }}>标的</th>
                  <th style={{ width: 78 }}>初选方向</th>
                  <th style={{ width: 120 }}>综合分</th>
                  <th style={{ width: 230 }}>拦截规则</th>
                  <th>说明</th>
                </tr>
              </thead>
              <tbody>
                {SIGNALS_BLOCKED.map((s) => (
                  <tr key={s.code} style={{ opacity: 0.92 }}>
                    <td>
                      <div style={{ display: "flex", flexDirection: "column", gap: 1 }}>
                        <span style={{ fontWeight: 500, textDecoration: "line-through", textDecorationColor: "var(--text-3)" }}>{s.name}</span>
                        <span className="mono" style={{ fontSize: 10.5, color: "var(--text-3)" }}>{s.code}</span>
                      </div>
                    </td>
                    <td><DirTag dir={s.dir} /></td>
                    <td><ScoreBar score={s.score} /></td>
                    <td><span className="badge badge-warn" style={{ height: 20, fontSize: 11 }}><span className="dot" />{s.blockedBy}</span></td>
                    <td style={{ color: "var(--text-2)", fontSize: 12 }}>{s.note}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Card>
        )}
      </div>
    </>
  );
}

function SignalRow({ s }) {
  return (
    <tr>
      <td>
        <div style={{ display: "flex", flexDirection: "column", gap: 1 }}>
          <span style={{ fontWeight: 500, color: "var(--text-1)" }}>{s.name}</span>
          <span className="mono" style={{ fontSize: 10.5, color: "var(--text-3)" }}>{s.code}</span>
        </div>
      </td>
      <td><DirTag dir={s.dir} /></td>
      <td><ScoreBar score={s.score} /></td>
      <td>
        <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
          {s.factors.map((f, i) => <Chip key={i} label={f[0]} value={f[1]} />)}
        </div>
      </td>
      <td style={{ color: "var(--text-2)", fontSize: 12, maxWidth: 280, whiteSpace: "normal" }}>{s.reason}</td>
    </tr>
  );
}

window.Signals = Signals;

// apps/desktop/src/pages/signals/Signals.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useTradingStore } from '../../stores/trading';
import { actionLabel, factorEntries, reasonLabel } from '../../lib/signals';
import { useAppStore } from '../../stores/app';
import { fmtSigned } from '../../lib/format';
import PageHero from '../../ui/PageHero.vue';
import Icon from '../../shell/Icon.vue';

const trading = useTradingStore();
const app = useAppStore();
const today = ref('');
const effective = ref('');
const tab = ref<'pass' | 'blocked'>('pass');

async function run() {
  if (!today.value || !effective.value) return;
  await trading.runPaper(today.value, effective.value);
}

function load() {
  if (today.value) trading.fetchSignals(today.value);
}

// 方向 → 徽章通道(系统色,Status 通道):买=ok 卖=warn 持有=idle。
// 与 actionClass(状态语义 class)解耦,仅供 .badge 着色;不占用盈亏色。
const DIR_BADGE: Record<string, string> = {
  buy: 'badge-ok',
  sell: 'badge-warn',
  hold: 'badge-idle',
};
function dirBadge(a: string): string {
  return DIR_BADGE[a] ?? 'badge-idle';
}
</script>

<template>
  <PageHero
    title="信号"
    :sub="`基于多因子模型 · 盘后打分出信号 + 模拟撮合 · 纪律高于模型${trading.date ? ' · ' + trading.date : ''}`"
  >
    <template #right>
      <button
        class="btn btn-primary btn-sm"
        :disabled="!today || !effective || trading.loading"
        @click="run"
      >
        <Icon name="refresh" :size="14" /> {{ trading.loading ? '运行中…' : '盘后跑一轮' }}
      </button>
    </template>
  </PageHero>

  <div class="page-body">
    <!-- 运行工具条(卡内) -->
    <div class="card card-pad">
      <div class="runner">
        <label class="field">
          <span class="field-cap cap">信号日 T</span>
          <input v-model="today" class="input mono" type="date" />
        </label>
        <label class="field">
          <span class="field-cap cap">生效日 T+1</span>
          <input v-model="effective" class="input mono" type="date" />
        </label>
        <span class="spacer" />
        <button
          class="btn btn-primary"
          :disabled="!today || !effective || trading.loading"
          @click="run"
        >
          <Icon name="refresh" :size="14" />
          {{ trading.loading ? '运行中…' : '盘后跑一轮(出信号 + 模拟撮合)' }}
        </button>
        <button class="btn btn-secondary" :disabled="!today || trading.loading" @click="load">
          查看该日信号
        </button>
      </div>
      <p v-if="trading.error" class="run-err status-err">{{ trading.error }}</p>
    </div>

    <!-- 分段切换 + 通道图例 -->
    <div class="bar">
      <div class="segmented" role="tablist">
        <button role="tab" :aria-selected="tab === 'pass'" @click="tab = 'pass'">
          入选信号 · {{ trading.activeSignals.length }}
        </button>
        <button role="tab" :aria-selected="tab === 'blocked'" @click="tab = 'blocked'">
          被风控拦截 · {{ trading.blockedSignals.length }}
        </button>
      </div>
      <div class="legend">
        <span class="ch-tag"><i style="background: var(--status-ok)" />方向=Status</span>
        <span class="ch-tag"><i style="background: var(--text-2)" />综合分=中性</span>
        <span class="ch-tag"><i style="background: var(--pnl-up)" />因子贡献=PnL</span>
      </div>
    </div>

    <!-- 入选信号 -->
    <div v-if="tab === 'pass'" class="card">
      <table v-if="trading.activeSignals.length" class="dt">
        <thead>
          <tr>
            <th style="width: 150px">标的</th>
            <th style="width: 88px">方向</th>
            <th class="num" style="width: 96px">综合分</th>
            <th>因子贡献</th>
            <th>入选原因</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="s in trading.activeSignals" :key="s.stock_code">
            <td>
              <div class="sym">
                <span v-if="s.stock_name" class="sym-name">{{ s.stock_name }}</span>
                <span class="col-code">{{ s.stock_code }}</span>
              </div>
            </td>
            <td>
              <span class="badge" :class="dirBadge(s.action)">
                <span class="dot" />{{ actionLabel(s.action) }}
              </span>
            </td>
            <td class="num score">{{ s.score?.toFixed(3) ?? '—' }}</td>
            <td>
              <div class="factors">
                <span
                  v-for="[f, v] in factorEntries(s.factor_breakdown).slice(0, 4)"
                  :key="f"
                  class="chip"
                >
                  {{ f }}
                  <span class="chip-val" :class="app.pnlClass(v)">{{ fmtSigned(v, 2) }}</span>
                </span>
                <span v-if="!factorEntries(s.factor_breakdown).length" class="cap dim">—</span>
              </div>
            </td>
            <td class="reason">{{ reasonLabel(s.reason) }}</td>
          </tr>
        </tbody>
      </table>
      <div v-else class="empty">
        <div class="empty-icon"><Icon name="signals" :size="20" /></div>
        <div class="empty-title">暂无生效信号</div>
        <div class="empty-desc">选信号日并「盘后跑一轮」,产出当日买卖信号与被风控拦截组。</div>
      </div>
    </div>

    <!-- 被风控拦截组 -->
    <div v-else class="card">
      <template v-if="trading.blockedSignals.length">
        <div class="block-note">
          <span class="block-ico status-warn"><Icon name="shield" :size="15" /></span>
          <span class="block-txt"
            >以下标的初选入围,但被风控闸拦截,不进入交易候选 —— 纪律高于模型。风控规则可在<b
              >设置 · 风控</b
            >中调整。</span
          >
        </div>
        <table class="dt">
          <thead>
            <tr>
              <th style="width: 150px">标的</th>
              <th style="width: 88px">初选方向</th>
              <th class="num" style="width: 96px">综合分</th>
              <th style="width: 230px">拦截规则</th>
              <th>说明</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="s in trading.blockedSignals" :key="s.stock_code" class="blocked-row">
              <td>
                <div class="sym">
                  <span v-if="s.stock_name" class="sym-name struck">{{ s.stock_name }}</span>
                  <span class="col-code">{{ s.stock_code }}</span>
                </div>
              </td>
              <td>
                <span class="badge" :class="dirBadge(s.action)">
                  <span class="dot" />{{ actionLabel(s.action) }}
                </span>
              </td>
              <td class="num score">{{ s.score?.toFixed(3) ?? '—' }}</td>
              <td>
                <span class="badge badge-warn"
                  ><span class="dot" />{{ reasonLabel(s.reason) }}</span
                >
              </td>
              <td class="reason">{{ reasonLabel(s.reason) }}</td>
            </tr>
          </tbody>
        </table>
      </template>
      <div v-else class="empty">
        <div class="empty-icon"><Icon name="shield" :size="20" /></div>
        <div class="empty-title">暂无被拦截的标的</div>
        <div class="empty-desc">初选入围但被风控闸拦下的标的会单独列在此处 —— 纪律高于模型。</div>
      </div>
    </div>

    <p class="disclaimer">
      仅供研究参考,非投资建议;模拟盘为纸面前向验证,不构成真实交易、不进行任何自动真实下单。
    </p>
  </div>
</template>

<style scoped>
.page-body {
  padding: 28px;
  display: flex;
  flex-direction: column;
  gap: 20px;
}

/* 运行工具条 */
.runner {
  display: flex;
  align-items: flex-end;
  gap: 14px;
  flex-wrap: wrap;
}
.field {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.field-cap {
  color: var(--text-2);
}
.field .input {
  width: 170px;
}
.spacer {
  flex: 1;
}
.run-err {
  margin: 14px 0 0;
  font-size: var(--fs-sub);
}

/* 分段切换 + 图例 */
.bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
}
.legend {
  display: flex;
  gap: 14px;
}
.ch-tag {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-size: 11px;
  color: var(--text-3);
  font-family: var(--font-mono);
}
.ch-tag i {
  width: 7px;
  height: 7px;
  border-radius: 2px;
  flex: none;
}

/* 标的列:名称 + 代码 */
.sym {
  display: flex;
  flex-direction: column;
  gap: 1px;
}
.sym-name {
  font-weight: 500;
  color: var(--text-1);
}
.sym-name.struck {
  text-decoration: line-through;
  text-decoration-color: var(--text-3);
}
.col-code {
  font-family: var(--font-mono);
  font-size: 10.5px;
  color: var(--text-3);
}

/* 综合分:中性灰阶,不占任何颜色通道 */
.score {
  color: var(--text-1);
  font-weight: 600;
}

/* 因子贡献 chips */
.factors {
  display: flex;
  gap: 6px;
  flex-wrap: wrap;
}
.reason {
  color: var(--text-2);
  font-size: 12px;
  white-space: normal;
  max-width: 320px;
}
.dim {
  color: var(--text-3);
}

/* 拦截组 */
.block-note {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px 16px;
  border-bottom: 0.5px solid var(--border);
}
.block-ico {
  display: inline-flex;
  flex: none;
}
.block-txt {
  font-size: 12.5px;
  color: var(--text-2);
}
.block-txt b {
  color: var(--text-1);
  font-weight: 500;
}
.blocked-row {
  opacity: 0.92;
}

.disclaimer {
  margin: 4px 0 0;
  color: var(--text-3);
  font-size: var(--fs-cap);
}
</style>
